version: '3.8'

services:
  postgres_db:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - poc1_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: poc1
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  poc1migration:
    container_name: poc1
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://root:root@postgres_db:5432/poc1"
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  poc1_volume:
